# Generated by Django 3.2.13 on 2023-10-28 21:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Products.vendor"
            ),
            preserve_default=False,
        ),
    ]
