# Generated by Django 3.2.13 on 2023-10-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='products',
        ),
    ]
